import datetime


def get_date_days_ago(days):
    return (datetime.datetime.utcnow() - datetime.timedelta(days=days)).isoformat()


def get_date_days_future(days):
    return (datetime.datetime.utcnow() + datetime.timedelta(days=days)).isoformat()


# --- USERS ---
USERS = [
    {
        "id": "user-1",
        "name": "Alex Johnson",
        "email": "alex.johnson@example.com",
        "password": "password123",
        "avatar": "https://picsum.photos/id/64/400/400",
        "bio": "Full-stack developer with a passion for decentralization and travel. Currently exploring the intersection of web3 and digital nomadism.",
        "is_host": True,
        "is_admin": True,
        "reputation_score": 450,
        "wallet_address": None,
    },
    {
        "id": "user-2",
        "name": "Maria Garcia",
        "email": "maria.garcia@example.com",
        "password": "password123",
        "avatar": "https://picsum.photos/id/91/400/400",
        "bio": "Content strategist and writer specializing in travel and tech. I love finding hidden gems in every city I visit.",
        "is_host": False,
        "reputation_score": 280,
        "wallet_address": "0x1234567890123456789012345678901234567890",
    },
    {
        "id": "user-3",
        "name": "Chen Wei",
        "email": "chen.wei@example.com",
        "password": "password123",
        "avatar": "https://picsum.photos/id/177/400/400",
        "bio": "Data scientist and AI enthusiast. Always looking for a quiet place to code and a good gym.",
        "is_host": True,
        "reputation_score": 120,
        "wallet_address": None,
    },
    {
        "id": "user-4",
        "name": "Sofia Rossi",
        "email": "sofia.rossi@example.com",
        "password": "password123",
        "avatar": "https://picsum.photos/id/219/400/400",
        "bio": "UI/UX designer with a love for minimalist aesthetics and historic cities. Believes good design can change the world.",
        "is_host": True,
        "reputation_score": 520,
        "wallet_address": None,
    },
    {
        "id": "user-5",
        "name": "Kenji Tanaka",
        "email": "kenji.tanaka@example.com",
        "password": "password123",
        "avatar": "https://picsum.photos/id/342/400/400",
        "bio": "Mindfulness coach and software engineer. I build apps that help people focus and find balance.",
        "is_host": True,
        "reputation_score": 310,
        "wallet_address": None,
    },
    {
        "id": "user-6",
        "name": "Chloe Dubois",
        "email": "chloe.dubois@example.com",
        "password": "password123",
        "avatar": "https://picsum.photos/id/399/400/400",
        "bio": "Web3 startup founder. Building the future of decentralized social media. Thrives in high-energy environments.",
        "is_host": False,
        "reputation_score": 180,
        "wallet_address": None,
    },
    {
        "id": "user-7",
        "name": "Lena Petrova",
        "email": "lena.petrova@example.com",
        "password": "password123",
        "avatar": "https://picsum.photos/id/453/400/400",
        "bio": "Wellness blogger and yoga instructor. Documenting my journey to find balance through travel and mindful practices.",
        "is_host": False,
        "reputation_score": 150,
        "wallet_address": None,
    },
    {
        "id": "user-8",
        "name": "David Chen",
        "email": "david.chen@example.com",
        "password": "password123",
        "avatar": "https://picsum.photos/id/338/400/400",
        "bio": "Remote software engineer specializing in backend systems. I love the freedom to work from anywhere with a good internet connection.",
        "is_host": False,
        "reputation_score": 230,
        "wallet_address": None,
    },
]

# --- NEIGHBORHOODS ---
NEIGHBORHOODS = [
    {
        "id": "n-1",
        "name": "Sonoran Desert",
        "city": "Scottsdale",
        "country": "USA",
        "lat": 33.68,
        "lng": -111.86,
        "image": "https://picsum.photos/id/15/800/600",
        "cost_of_living_index": 70,
        "walkability_score": 20,
        "safety_score": 90,
        "visa_friendliness": "Easy",
    },
    {
        "id": "n-2",
        "name": "Nimmanhaemin",
        "city": "Chiang Mai",
        "country": "Thailand",
        "lat": 18.79,
        "lng": 98.96,
        "image": "https://picsum.photos/id/20/800/600",
        "cost_of_living_index": 30,
        "walkability_score": 90,
        "safety_score": 80,
        "visa_friendliness": "Medium",
    },
    {
        "id": "n-3",
        "name": "Alfama",
        "city": "Lisbon",
        "country": "Portugal",
        "lat": 38.71,
        "lng": -9.12,
        "image": "https://picsum.photos/id/28/800/600",
        "cost_of_living_index": 50,
        "walkability_score": 95,
        "safety_score": 85,
        "visa_friendliness": "Easy",
    },
    {
        "id": "n-4",
        "name": "Ubud",
        "city": "Ubud",
        "country": "Indonesia",
        "lat": -8.50,
        "lng": 115.26,
        "image": "https://picsum.photos/id/29/800/600",
        "cost_of_living_index": 25,
        "walkability_score": 70,
        "safety_score": 88,
        "visa_friendliness": "Medium",
    },
    {
        "id": "n-5",
        "name": "La Veleta",
        "city": "Tulum",
        "country": "Mexico",
        "lat": 20.20,
        "lng": -87.47,
        "image": "https://picsum.photos/id/47/800/600",
        "cost_of_living_index": 60,
        "walkability_score": 50,
        "safety_score": 75,
        "visa_friendliness": "Easy",
    },
    {
        "id": "n-6",
        "name": "Roma Norte",
        "city": "Mexico City",
        "country": "Mexico",
        "lat": 19.41,
        "lng": -99.16,
        "image": "https://picsum.photos/id/55/800/600",
        "cost_of_living_index": 45,
        "walkability_score": 98,
        "safety_score": 78,
        "visa_friendliness": "Easy",
    },
    {
        "id": "n-7",
        "name": "Mitte",
        "city": "Berlin",
        "country": "Germany",
        "lat": 52.52,
        "lng": 13.40,
        "image": "https://picsum.photos/id/65/800/600",
        "cost_of_living_index": 65,
        "walkability_score": 96,
        "safety_score": 82,
        "visa_friendliness": "Easy",
    },
    {
        "id": "n-8",
        "name": "Tucson",
        "city": "Tucson",
        "country": "USA",
        "lat": 32.22,
        "lng": -110.97,
        "image": "https://picsum.photos/id/100/800/600",
        "cost_of_living_index": 60,
        "walkability_score": 42,
        "safety_score": 70,
        "visa_friendliness": "Easy",
    },
]

# --- LISTINGS ---
LISTINGS = [
    {
        "id": "listing-1",
        "owner_id": "user-1",
        "name": "Futuristic Desert Pod",
        "property_type": "Pod",
        "city": "Scottsdale",
        "country": "USA",
        "description": "A state-of-the-art pod for deep work and stargazing. Features high-speed satellite internet and a minimalist design.",
        "price_usd": 4500,
        "features": [
            "wifi",
            "desk",
            "kitchenette",
            "stargazing roof",
            "air conditioning",
        ],
        "images": [
            "https://picsum.photos/id/165/800/600",
            "https://picsum.photos/id/174/800/600",
        ],
        "guest_capacity": 1,
        "bedrooms": 1,
        "bathrooms": 1,
        "hub_id": "hub-arizona",
    },
    {
        "id": "listing-2",
        "owner_id": "user-1",
        "name": "Minimalist Desert Loft",
        "property_type": "Loft",
        "city": "Scottsdale",
        "country": "USA",
        "description": "Clean, open-plan loft with stunning views of the Sonoran desert. Perfect for creative retreats.",
        "price_usd": 3200,
        "features": ["wifi", "desk", "kitchen", "air conditioning", "pool"],
        "images": [
            "https://picsum.photos/id/188/800/600",
            "https://picsum.photos/id/237/800/600",
        ],
        "guest_capacity": 2,
        "bedrooms": 1,
        "bathrooms": 1,
        "hub_id": "hub-arizona",
    },
    {
        "id": "listing-3",
        "owner_id": "user-4",
        "name": "Historic Alfama Flat",
        "property_type": "Apartment",
        "city": "Lisbon",
        "country": "Portugal",
        "description": "Charming flat in the heart of historic Alfama. Cobblestone streets, Fado music, and incredible food at your doorstep.",
        "price_usd": 2800,
        "features": ["wifi", "desk", "kitchen", "balcony", "city view"],
        "images": [
            "https://picsum.photos/id/271/800/600",
            "https://picsum.photos/id/334/800/600",
        ],
        "guest_capacity": 3,
        "bedrooms": 2,
        "bathrooms": 1,
        "hub_id": "hub-lisbon",
    },
    {
        "id": "listing-4",
        "owner_id": "user-4",
        "name": "Bright Studio with River View",
        "property_type": "Studio",
        "city": "Lisbon",
        "country": "Portugal",
        "description": "Modern and bright studio with a beautiful view of the Tagus River. Close to creative hubs and galleries.",
        "price_usd": 2100,
        "features": ["wifi", "desk", "kitchenette", "city view"],
        "images": [
            "https://picsum.photos/id/318/800/600",
            "https://picsum.photos/id/338/800/600",
        ],
        "guest_capacity": 2,
        "bedrooms": 0,
        "bathrooms": 1,
        "hub_id": "hub-lisbon",
    },
    {
        "id": "listing-5",
        "owner_id": "user-5",
        "name": "Lush Garden Villa",
        "property_type": "Villa",
        "city": "Ubud",
        "country": "Indonesia",
        "description": "A serene villa surrounded by lush tropical gardens. Includes access to a yoga shala and daily breakfast.",
        "price_usd": 3500,
        "features": ["wifi", "desk", "kitchen", "pool", "gym", "air conditioning"],
        "images": [
            "https://picsum.photos/id/366/800/600",
            "https://picsum.photos/id/376/800/600",
        ],
        "guest_capacity": 4,
        "bedrooms": 2,
        "bathrooms": 2,
        "hub_id": "hub-bali",
    },
    {
        "id": "listing-6",
        "owner_id": "user-4",
        "name": "Rooftop Apartment for Creators",
        "property_type": "Apartment",
        "city": "Lisbon",
        "country": "Portugal",
        "description": "Penthouse apartment with a private rooftop terrace. Part of our Creator-in-Residence program.",
        "price_usd": 3300,
        "features": ["wifi", "desk", "kitchen", "balcony"],
        "images": [
            "https://picsum.photos/id/385/800/600",
            "https://picsum.photos/id/403/800/600",
        ],
        "guest_capacity": 2,
        "bedrooms": 1,
        "bathrooms": 1,
        "hub_id": "hub-lisbon",
    },
    {
        "id": "listing-7",
        "owner_id": "user-5",
        "name": "Rice Paddy View Bungalow",
        "property_type": "Bungalow",
        "city": "Ubud",
        "country": "Indonesia",
        "description": "Simple and peaceful bungalow with an open-air workspace overlooking the rice paddies.",
        "price_usd": 1600,
        "features": ["wifi", "desk", "kitchenette", "balcony"],
        "images": [
            "https://picsum.photos/id/416/800/600",
            "https://picsum.photos/id/110/800/600",
        ],
        "guest_capacity": 2,
        "bedrooms": 1,
        "bathrooms": 1,
        "hub_id": "hub-bali",
    },
    {
        "id": "listing-8",
        "owner_id": "user-3",
        "name": "Modern Condo in Nimman",
        "property_type": "Apartment",
        "city": "Chiang Mai",
        "country": "Thailand",
        "description": "Sleek, modern condo in the heart of the trendy Nimmanhaemin neighborhood. Steps from cafes, coworking spaces, and nightlife.",
        "price_usd": 1800,
        "features": ["wifi", "desk", "kitchenette", "pool", "gym", "air conditioning"],
        "images": [
            "https://picsum.photos/id/119/800/600",
            "https://picsum.photos/id/160/800/600",
        ],
        "guest_capacity": 2,
        "bedrooms": 1,
        "bathrooms": 1,
        "hub_id": "hub-chiang-mai",
    },
    {
        "id": "listing-9",
        "owner_id": "user-5",
        "name": "Ubud Jungle Loft (Experience Venue)",
        "property_type": "Loft",
        "city": "Ubud",
        "country": "Indonesia",
        "description": "Stunning jungle loft used as a venue for wellness experiences. Open-air design, yoga platform, and serene atmosphere.",
        "price_usd": 2500,
        "features": ["wifi", "kitchen", "pool"],
        "images": [
            "https://picsum.photos/id/169/800/600"
        ],
        "guest_capacity": 10,
        "bedrooms": 1,
        "bathrooms": 2,
        "hub_id": "hub-bali",
    },
    {
        "id": "listing-10",
        "owner_id": "user-3",
        "name": "Digital Nomad Basecamp",
        "property_type": "Apartment",
        "city": "Chiang Mai",
        "country": "Thailand",
        "description": "A practical and affordable basecamp for digital nomads. Ergonomic setup, fast internet, and a quiet building.",
        "price_usd": 1200,
        "features": ["wifi", "desk", "kitchenette"],
        "images": [
            "https://picsum.photos/id/180/800/600"
        ],
        "guest_capacity": 1,
        "bedrooms": 1,
        "bathrooms": 1,
        "hub_id": "hub-chiang-mai",
    },
    {
        "id": "listing-11",
        "owner_id": "user-1",
        "name": "Casa de las Flores",
        "property_type": "House",
        "city": "Mexico City",
        "country": "Mexico",
        "description": "Colorful and vibrant house in the heart of Roma Norte. Perfect for exploring the city's art and food scene.",
        "price_usd": 3800,
        "features": ["wifi", "desk", "kitchen", "balcony"],
        "images": [
            "https://picsum.photos/id/193/800/600"
        ],
        "guest_capacity": 4,
        "bedrooms": 2,
        "bathrooms": 2,
        "hub_id": "hub-mexico-city",
    },
    {
        "id": "listing-12",
        "owner_id": "user-1",
        "name": "Berlin Bauhaus Loft",
        "property_type": "Loft",
        "city": "Berlin",
        "country": "Germany",
        "description": "Minimalist loft in Mitte inspired by Bauhaus design. High ceilings, lots of natural light, and close to galleries.",
        "price_usd": 3100,
        "features": ["wifi", "desk", "kitchen", "elevator"],
        "images": [
            "https://picsum.photos/id/200/800/600"
        ],
        "guest_capacity": 2,
        "bedrooms": 1,
        "bathrooms": 1,
        "hub_id": "hub-berlin",
    },
    {
        "id": "listing-13",
        "owner_id": "user-5",
        "name": "Miraval Wellness Villa (Virtual)",
        "property_type": "Villa",
        "city": "Tucson",
        "country": "USA",
        "description": "A virtual booking for a villa at the Miraval Arizona resort, representing a slot in their wellness program.",
        "price_usd": 7000,
        "features": ["pool", "gym", "spa"],
        "images": [
            "https://picsum.photos/id/209/800/600"
        ],
        "guest_capacity": 2,
        "bedrooms": 1,
        "bathrooms": 1,
        "hub_id": "v-hub-miraval-arizona",
    },
]

# --- STATIC HUBS ---
HUBS = [
    {
        "id": "hub-arizona",
        "name": "NomadNest Arizona",
        "mission": "A desert oasis for deep work, connection, and stargazing.",
        "type": "co-living",
        "logo": "https://picsum.photos/id/42/800/600",
        "charter": "Our charter emphasizes sustainable living and harmony with the desert environment.",
        "member_ids": ["user-1", "user-2"],
        "listing_ids": ["listing-1", "listing-2"],
        "sustainability_score": 85,
        "lat": 33.68,
        "lng": -111.86,
        "tags": ["co-living", "desert", "deep-work", "nature-retreat"],
    },
    {
        "id": "hub-chiang-mai",
        "name": "NomadNest Chiang Mai",
        "mission": "The ultimate hub for digital nomads seeking community, affordability, and amazing food.",
        "type": "co-living",
        "logo": "https://picsum.photos/id/48/800/600",
        "charter": "A charter focused on collaboration, skill-sharing, and supporting local businesses.",
        "member_ids": ["user-3", "user-8"],
        "listing_ids": ["listing-8", "listing-10"],
        "sustainability_score": 70,
        "lat": 18.79,
        "lng": 98.96,
        "tags": ["co-living", "digital-nomad", "foodie", "city-hub"],
    },
    {
        "id": "hub-lisbon",
        "name": "Creator's Canvas Lisbon",
        "mission": "A vibrant home for artists, designers, and creators in the heart of Europe's most creative city.",
        "type": "co-living",
        "logo": "https://picsum.photos/id/49/800/600",
        "charter": "We empower creators by providing the spaces, tools, and connections they need to thrive.",
        "member_ids": ["user-4", "user-6"],
        "listing_ids": ["listing-3", "listing-4", "listing-6"],
        "sustainability_score": 78,
        "lat": 38.71,
        "lng": -9.12,
        "tags": ["co-living", "creative", "art", "city-hub"],
    },
    {
        "id": "hub-bali",
        "name": "Aura Wellness Hub Bali",
        "mission": "Find your balance. A sanctuary for wellness, mindfulness, and productive work in the tranquility of Ubud.",
        "type": "wellness-hub",
        "logo": "https://picsum.photos/id/57/800/600",
        "charter": "To provide a harmonious environment for personal growth, healing, and connection.",
        "member_ids": ["user-5", "user-7"],
        "listing_ids": ["listing-5", "listing-7", "listing-9"],
        "sustainability_score": 92,
        "lat": -8.50,
        "lng": 115.26,
        "tags": ["wellness-hub", "yoga", "health-retreat", "nature-retreat"],
    },
    {
        "id": "hub-mexico-city",
        "name": "The Commons CDMX",
        "mission": "Live like a local in the heart of one of the world's most exciting cultural capitals.",
        "type": "private-stay",
        "logo": "https://picsum.photos/id/58/800/600",
        "charter": "Fostering genuine local connections by integrating with the urban fabric.",
        "member_ids": [],
        "listing_ids": ["listing-11"],
        "sustainability_score": 65,
        "lat": 19.41,
        "lng": -99.16,
        "tags": ["private-stay", "culture", "foodie", "city-hub"],
    },
    {
        "id": "hub-berlin",
        "name": "The Commons Berlin",
        "mission": "A base for creatives and tech professionals in the vibrant heart of Berlin's Mitte district.",
        "type": "private-stay",
        "logo": "https://picsum.photos/id/59/800/600",
        "charter": "Fostering genuine local connections by integrating with the urban fabric.",
        "member_ids": [],
        "listing_ids": ["listing-12"],
        "sustainability_score": 72,
        "lat": 52.52,
        "lng": 13.40,
        "tags": ["private-stay", "tech", "design", "city-hub"],
    },
    {
        "id": "hub-santa-teresa",
        "name": "Coastal Collective Santa Teresa",
        "mission": "Pura vida for the digital nomad. Find your flow between surf sessions and deep work.",
        "type": "wellness-hub",
        "logo": "https://picsum.photos/id/60/800/600",
        "charter": "To provide a balanced lifestyle of work, wellness, and adventure in a world-class surf destination.",
        "member_ids": [],
        "listing_ids": [],
        "sustainability_score": 88,
        "lat": 9.64,
        "lng": -85.16,
        "tags": ["wellness-hub", "surf", "nature-retreat", "beach"],
    },
    {
        "id": "hub-ericeira",
        "name": "Coastal Collective Ericeira",
        "mission": "Europe's premier surf reserve meets a thriving creative and professional community.",
        "type": "wellness-hub",
        "logo": "https://picsum.photos/id/63/800/600",
        "charter": "To blend high-performance work with the raw energy of the Atlantic coast.",
        "member_ids": [],
        "listing_ids": [],
        "sustainability_score": 82,
        "lat": 38.96,
        "lng": -9.41,
        "tags": ["wellness-hub", "surf", "co-living", "beach"],
    },
]

# --- STATIC EXPERIENCES ---
EXPERIENCES = [
    {
        "id": "res-1",
        "type": "residency",
        "name": "Web3 & Decentralization Deep Dive",
        "theme": "Technology",
        "mission": "A 3-month residency for developers and founders building the next generation of the internet.",
        "curator_id": "user-1",
        "listing_ids": ["listing-1", "listing-2"],
        "start_date": "2024-10-01",
        "end_date": "2024-12-20",
        "image": "https://picsum.photos/id/211/800/600",
    },
    {
        "id": "res-2",
        "type": "residency",
        "name": "Creator-in-Residence Program",
        "theme": "Art & Design",
        "mission": "For digital artists, UI/UX designers, and content creators.",
        "curator_id": "user-4",
        "listing_ids": ["listing-3", "listing-4"],
        "start_date": "2024-09-01",
        "end_date": "2024-11-30",
        "image": "https://picsum.photos/id/225/800/600",
    },
    {
        "id": "user-exp-1",
        "type": "retreat",
        "name": "Sunrise Yoga Workshop",
        "theme": "Yoga & Wellness",
        "mission": "A weekend workshop focused on Vinyasa flow, meditation, and connecting with nature.",
        "curator_id": "user-7",
        "listing_ids": ["listing-9"],
        "start_date": "2024-08-16",
        "end_date": "2024-08-18",
        "image": "https://picsum.photos/id/250/800/600",
    },
]

# --- REVIEWS ---
REVIEWS = [
    {
        "id": "rev-1",
        "listing_id": "listing-1",
        "author_id": "user-2",
        "rating": 9.5,
        "comment": "Absolutely incredible! The perfect place for deep work. The desert views are inspiring, and the satellite internet was surprisingly fast. Can't wait to come back.",
    },
    {
        "id": "rev-2",
        "listing_id": "listing-1",
        "author_id": "user-3",
        "rating": 10,
        "comment": "A truly unique experience. The pod was futuristic and comfortable. Complete silence at night for perfect sleep.",
    },
    {
        "id": "rev-3",
        "listing_id": "listing-3",
        "author_id": "user-6",
        "rating": 9,
        "comment": "Loved the vibe of this place! Met so many interesting creators. The shared studio is a huge plus. The location in Alfama is unbeatable.",
    },
]

# --- TASKS ---
TASKS = [
    {
        "id": "task-1",
        "title": "Organize Weekly Community Dinner",
        "description": "Plan, shop for, and cook a meal for 20 people.",
        "status": "To Do",
        "assignee_id": None,
        "reward": 50,
        "xp_category": "Community",
    },
    {
        "id": "task-2",
        "title": "Fix the WiFi Repeater",
        "description": "The repeater on the 2nd floor is acting up. Needs a reboot and maybe a firmware update.",
        "status": "In Progress",
        "assignee_id": "user-1",
        "reward": 30,
        "xp_category": "Technical",
    },
    {
        "id": "task-3",
        "title": "Test New VR Headset",
        "description": "Provide feedback on the new VR equipment for the media room.",
        "status": "Done",
        "assignee_id": "user-2",
        "reward": 30,
        "xp_category": "Community",
    },
    {
        "id": "task-4",
        "title": "Write a welcome guide for the Lisbon hub",
        "description": "Create a short guide for new members with tips on the best local spots.",
        "status": "To Do",
        "assignee_id": None,
        "reward": 40,
        "xp_category": "Community",
    },
    {
        "id": "task-5",
        "title": "Set up new shared monitor",
        "description": "Unbox and set up the new 4K monitor in the coworking space.",
        "status": "In Progress",
        "assignee_id": "user-2",
        "reward": 20,
        "xp_category": "Technical",
    },
    {
        "id": "task-6",
        "title": "Water the community garden",
        "description": "Give the plants on the rooftop a good watering.",
        "status": "Done",
        "assignee_id": "user-5",
        "reward": 10,
        "xp_category": "Community",
    },
]

# --- BOOKINGS ---
BOOKINGS = [
    {
        "id": "booking-1",
        "user_id": "user-1",
        "listing_id": "listing-1",
        "check_in": get_date_days_ago(30),
        "check_out": get_date_days_ago(23),
        "status": "completed",
        "total_price": 840.0,
        "guests": 1,
        "special_requests": "Early check-in if possible",
    },
    {
        "id": "booking-2",
        "user_id": "user-1",
        "listing_id": "listing-3",
        "check_in": get_date_days_future(7),
        "check_out": get_date_days_future(14),
        "status": "confirmed",
        "total_price": 980.0,
        "guests": 1,
        "special_requests": "Quiet room preferred",
    },
    {
        "id": "booking-3",
        "user_id": "user-2",
        "listing_id": "listing-2",
        "check_in": get_date_days_ago(14),
        "check_out": get_date_days_ago(7),
        "status": "completed",
        "total_price": 1050.0,
        "guests": 2,
        "special_requests": None,
    },
    {
        "id": "booking-4",
        "user_id": "user-3",
        "listing_id": "listing-1",
        "check_in": get_date_days_future(21),
        "check_out": get_date_days_future(35),
        "status": "pending",
        "total_price": 1680.0,
        "guests": 1,
        "special_requests": "Need fast internet for work calls",
    },
    {
        "id": "booking-5",
        "user_id": "user-4",
        "listing_id": "listing-4",
        "check_in": get_date_days_ago(60),
        "check_out": get_date_days_ago(45),
        "status": "completed",
        "total_price": 2250.0,
        "guests": 1,
        "special_requests": None,
    },
]

# --- MESSAGE THREADS ---
MESSAGE_THREADS = [
    {
        "id": "thread-1",
        "participant_ids": ["user-1", "user-2"],
        "listing_id": "listing-1",
        "created_at": get_date_days_ago(5),
        "messages": [
            {"sender_id": "user-2", "content": "Hi! I'm interested in your listing in Lisbon. Is it available next month?", "sent_at": get_date_days_ago(5)},
            {"sender_id": "user-1", "content": "Hello Maria! Yes, I have availability from the 15th onwards. Would that work for you?", "sent_at": get_date_days_ago(5)},
            {"sender_id": "user-2", "content": "Perfect! I'll book for 2 weeks starting the 15th.", "sent_at": get_date_days_ago(4)},
        ],
    },
    {
        "id": "thread-2",
        "participant_ids": ["user-1", "user-3"],
        "listing_id": None,
        "created_at": get_date_days_ago(10),
        "messages": [
            {"sender_id": "user-3", "content": "Hey Alex, wanted to connect about the co-living community. I'm looking for a place with good coworking facilities.", "sent_at": get_date_days_ago(10)},
            {"sender_id": "user-1", "content": "Hi Chen! Our hub in Lisbon has great coworking space - dedicated desks and meeting rooms.", "sent_at": get_date_days_ago(9)},
            {"sender_id": "user-3", "content": "Sounds great. What's the internet speed like?", "sent_at": get_date_days_ago(9)},
            {"sender_id": "user-1", "content": "We have 500 Mbps fiber with backup. Never had issues with video calls.", "sent_at": get_date_days_ago(8)},
        ],
    },
    {
        "id": "thread-3",
        "participant_ids": ["user-1", "user-4"],
        "listing_id": "listing-3",
        "created_at": get_date_days_ago(2),
        "messages": [
            {"sender_id": "user-4", "content": "Hi, I'm a designer looking for a creative space. Does the Bali listing have good natural light?", "sent_at": get_date_days_ago(2)},
            {"sender_id": "user-1", "content": "Hi Sofia! Yes, the Bali space has floor-to-ceiling windows facing the garden. Perfect for creative work!", "sent_at": get_date_days_ago(1)},
        ],
    },
]

# --- APPLICATIONS ---
APPLICATIONS = [
    {
        "id": "app-1",
        "user_id": "user-2",
        "hub_id": "hub-lisbon",
        "status": "approved",
        "message": "I'm a content strategist looking to join a community of like-minded digital nomads. I can contribute with content creation and social media management.",
        "created_at": get_date_days_ago(45),
    },
    {
        "id": "app-2",
        "user_id": "user-3",
        "hub_id": "hub-bali",
        "status": "pending",
        "message": "Data scientist seeking a quiet workspace with reliable internet. Happy to help with tech support and data analysis workshops.",
        "created_at": get_date_days_ago(3),
    },
    {
        "id": "app-3",
        "user_id": "user-6",
        "hub_id": "hub-lisbon",
        "status": "pending",
        "message": "Web3 founder looking for a community to connect with while building my startup. Can offer sessions on blockchain and decentralized technologies.",
        "created_at": get_date_days_ago(1),
    },
    {
        "id": "app-4",
        "user_id": "user-7",
        "hub_id": "hub-chiang-mai",
        "status": "approved",
        "message": "Yoga instructor and wellness blogger. Would love to contribute with morning yoga sessions for the community.",
        "created_at": get_date_days_ago(30),
    },
]

# --- SERVICES ---
SERVICES = [
    {
        "id": "service-1",
        "hub_id": "hub-lisbon",
        "name": "Airport Pickup",
        "description": "Complimentary pickup from Lisbon airport for stays of 7+ nights",
        "price": 0,
        "category": "transport",
    },
    {
        "id": "service-2",
        "hub_id": "hub-lisbon",
        "name": "Coworking Day Pass",
        "description": "Full day access to coworking space with meeting room credits",
        "price": 25,
        "category": "workspace",
    },
    {
        "id": "service-3",
        "hub_id": "hub-bali",
        "name": "Laundry Service",
        "description": "Weekly laundry service included with all stays",
        "price": 0,
        "category": "amenity",
    },
    {
        "id": "service-4",
        "hub_id": "hub-chiang-mai",
        "name": "Scooter Rental",
        "description": "Daily scooter rental for exploring the island",
        "price": 15,
        "category": "transport",
    },
    {
        "id": "service-5",
        "hub_id": "hub-lisbon",
        "name": "Chef's Dinner",
        "description": "Weekly community dinner prepared by local chef",
        "price": 20,
        "category": "food",
    },
    {
        "id": "service-6",
        "hub_id": "hub-bali",
        "name": "Daily Yoga Sessions",
        "description": "Morning vinyasa flow and sunset yin yoga with certified instructors",
        "price": 0,
        "category": "wellness",
    },
    {
        "id": "service-7",
        "hub_id": "hub-bali",
        "name": "Balinese Spa & Healing",
        "description": "Traditional Balinese massage, sound healing, and ayurvedic consultations",
        "price": 45,
        "category": "wellness",
    },
    {
        "id": "service-8",
        "hub_id": "hub-bali",
        "name": "Organic Meal Plan",
        "description": "Farm-to-table breakfast and lunch sourced from local organic farms",
        "price": 30,
        "category": "food",
    },
]

# --- COMMUNITY EVENTS ---
EVENTS = [
    {
        "id": "event-1",
        "hub_id": "hub-lisbon",
        "name": "Sunday Brunch & Networking",
        "description": "Weekly community brunch on the rooftop terrace. Great way to meet fellow residents!",
        "date": get_date_days_future(3),
        "location": "Rooftop Terrace",
        "capacity": 20,
        "attendee_ids": ["user-1", "user-2", "user-5"],
    },
    {
        "id": "event-2",
        "hub_id": "hub-lisbon",
        "name": "Pitch Night",
        "description": "Monthly event where residents can pitch their projects and get feedback from the community.",
        "date": get_date_days_future(10),
        "location": "Main Coworking Space",
        "capacity": 30,
        "attendee_ids": ["user-1", "user-3", "user-6"],
    },
    {
        "id": "event-3",
        "hub_id": "hub-bali",
        "name": "Morning Yoga Session",
        "description": "Start your day with a guided yoga session overlooking the garden.",
        "date": get_date_days_future(1),
        "location": "Garden Pavilion",
        "capacity": 15,
        "attendee_ids": ["user-4", "user-7"],
    },
    {
        "id": "event-4",
        "hub_id": "hub-chiang-mai",
        "name": "Sunset Beach Meetup",
        "description": "Casual gathering at the beach to watch the sunset and share stories.",
        "date": get_date_days_future(5),
        "location": "Echo Beach",
        "capacity": 25,
        "attendee_ids": ["user-5"],
    },
    {
        "id": "event-5",
        "hub_id": "hub-lisbon",
        "name": "Tech Talk: AI in 2024",
        "description": "Discussion on the latest AI trends and their impact on remote work.",
        "date": get_date_days_future(14),
        "location": "Conference Room",
        "capacity": 20,
        "attendee_ids": ["user-1", "user-3"],
    },
]

