"""
Seed data for Cost of Living calculator.
Run this to populate the city_living_costs table.
"""
from backend.database import SessionLocal
from backend import models
import uuid


CITY_DATA = [
    # Southeast Asia
    {
        "city": "Chiang Mai",
        "country": "Thailand",
        "country_code": "TH",
        "rent_studio": 350,
        "rent_1br": 500,
        "coworking": 100,
        "meal_cheap": 2,
        "meal_mid": 8,
        "coffee": 2,
        "groceries": 150,
        "transport": 30,
        "utilities": 50,
        "internet": 25,
        "gym": 30,
        "wifi_quality": 8,
        "safety_score": 8,
        "weather_score": 7,
        "nightlife_score": 6,
        "outdoor_score": 8,
        "english_level": 5,
        "nomad_score": 9,
        "visa_type": "tourist",
        "visa_duration_days": 60,
        "timezone": "UTC+7",
    },
    {
        "city": "Bangkok",
        "country": "Thailand",
        "country_code": "TH",
        "rent_studio": 500,
        "rent_1br": 750,
        "coworking": 150,
        "meal_cheap": 3,
        "meal_mid": 12,
        "coffee": 3,
        "groceries": 200,
        "transport": 50,
        "utilities": 80,
        "internet": 25,
        "gym": 50,
        "wifi_quality": 9,
        "safety_score": 7,
        "weather_score": 6,
        "nightlife_score": 9,
        "outdoor_score": 5,
        "english_level": 6,
        "nomad_score": 8.5,
        "visa_type": "tourist",
        "visa_duration_days": 60,
        "timezone": "UTC+7",
    },
    {
        "city": "Bali",
        "country": "Indonesia",
        "country_code": "ID",
        "rent_studio": 600,
        "rent_1br": 900,
        "coworking": 180,
        "meal_cheap": 4,
        "meal_mid": 15,
        "coffee": 3,
        "groceries": 200,
        "transport": 80,
        "utilities": 100,
        "internet": 40,
        "gym": 40,
        "wifi_quality": 7,
        "safety_score": 8,
        "weather_score": 8,
        "nightlife_score": 7,
        "outdoor_score": 9,
        "english_level": 6,
        "nomad_score": 9,
        "visa_type": "tourist",
        "visa_duration_days": 60,
        "timezone": "UTC+8",
    },
    {
        "city": "Ho Chi Minh City",
        "country": "Vietnam",
        "country_code": "VN",
        "rent_studio": 400,
        "rent_1br": 600,
        "coworking": 100,
        "meal_cheap": 2,
        "meal_mid": 8,
        "coffee": 1.5,
        "groceries": 150,
        "transport": 30,
        "utilities": 50,
        "internet": 20,
        "gym": 30,
        "wifi_quality": 8,
        "safety_score": 7,
        "weather_score": 6,
        "nightlife_score": 8,
        "outdoor_score": 5,
        "english_level": 5,
        "nomad_score": 8,
        "visa_type": "tourist",
        "visa_duration_days": 90,
        "timezone": "UTC+7",
    },
    # Europe
    {
        "city": "Lisbon",
        "country": "Portugal",
        "country_code": "PT",
        "rent_studio": 1000,
        "rent_1br": 1400,
        "coworking": 200,
        "meal_cheap": 8,
        "meal_mid": 25,
        "coffee": 1.5,
        "groceries": 250,
        "transport": 40,
        "utilities": 100,
        "internet": 35,
        "gym": 40,
        "wifi_quality": 9,
        "safety_score": 9,
        "weather_score": 9,
        "nightlife_score": 8,
        "outdoor_score": 8,
        "english_level": 8,
        "nomad_score": 9,
        "visa_type": "schengen",
        "visa_duration_days": 90,
        "timezone": "UTC+0",
    },
    {
        "city": "Barcelona",
        "country": "Spain",
        "country_code": "ES",
        "rent_studio": 1100,
        "rent_1br": 1500,
        "coworking": 220,
        "meal_cheap": 10,
        "meal_mid": 30,
        "coffee": 2,
        "groceries": 280,
        "transport": 50,
        "utilities": 120,
        "internet": 40,
        "gym": 50,
        "wifi_quality": 9,
        "safety_score": 7,
        "weather_score": 9,
        "nightlife_score": 9,
        "outdoor_score": 8,
        "english_level": 6,
        "nomad_score": 8,
        "visa_type": "schengen",
        "visa_duration_days": 90,
        "timezone": "UTC+1",
    },
    {
        "city": "Berlin",
        "country": "Germany",
        "country_code": "DE",
        "rent_studio": 1000,
        "rent_1br": 1400,
        "coworking": 250,
        "meal_cheap": 10,
        "meal_mid": 25,
        "coffee": 3,
        "groceries": 250,
        "transport": 90,
        "utilities": 150,
        "internet": 35,
        "gym": 35,
        "wifi_quality": 9,
        "safety_score": 8,
        "weather_score": 5,
        "nightlife_score": 10,
        "outdoor_score": 6,
        "english_level": 9,
        "nomad_score": 8,
        "visa_type": "schengen",
        "visa_duration_days": 90,
        "timezone": "UTC+1",
    },
    {
        "city": "Tbilisi",
        "country": "Georgia",
        "country_code": "GE",
        "rent_studio": 400,
        "rent_1br": 600,
        "coworking": 80,
        "meal_cheap": 5,
        "meal_mid": 15,
        "coffee": 2,
        "groceries": 150,
        "transport": 20,
        "utilities": 50,
        "internet": 15,
        "gym": 25,
        "wifi_quality": 8,
        "safety_score": 8,
        "weather_score": 7,
        "nightlife_score": 7,
        "outdoor_score": 8,
        "english_level": 5,
        "nomad_score": 8.5,
        "visa_type": "visa_free",
        "visa_duration_days": 365,
        "timezone": "UTC+4",
    },
    # Latin America
    {
        "city": "Medellin",
        "country": "Colombia",
        "country_code": "CO",
        "rent_studio": 500,
        "rent_1br": 800,
        "coworking": 120,
        "meal_cheap": 4,
        "meal_mid": 15,
        "coffee": 1.5,
        "groceries": 180,
        "transport": 30,
        "utilities": 60,
        "internet": 30,
        "gym": 30,
        "wifi_quality": 8,
        "safety_score": 6,
        "weather_score": 10,
        "nightlife_score": 9,
        "outdoor_score": 8,
        "english_level": 4,
        "nomad_score": 9,
        "visa_type": "tourist",
        "visa_duration_days": 180,
        "timezone": "UTC-5",
    },
    {
        "city": "Mexico City",
        "country": "Mexico",
        "country_code": "MX",
        "rent_studio": 700,
        "rent_1br": 1000,
        "coworking": 150,
        "meal_cheap": 5,
        "meal_mid": 18,
        "coffee": 2.5,
        "groceries": 200,
        "transport": 30,
        "utilities": 60,
        "internet": 30,
        "gym": 40,
        "wifi_quality": 8,
        "safety_score": 5,
        "weather_score": 8,
        "nightlife_score": 9,
        "outdoor_score": 6,
        "english_level": 4,
        "nomad_score": 8.5,
        "visa_type": "tourist",
        "visa_duration_days": 180,
        "timezone": "UTC-6",
    },
    {
        "city": "Buenos Aires",
        "country": "Argentina",
        "country_code": "AR",
        "rent_studio": 400,
        "rent_1br": 600,
        "coworking": 80,
        "meal_cheap": 5,
        "meal_mid": 15,
        "coffee": 2,
        "groceries": 150,
        "transport": 15,
        "utilities": 30,
        "internet": 20,
        "gym": 20,
        "wifi_quality": 7,
        "safety_score": 5,
        "weather_score": 8,
        "nightlife_score": 9,
        "outdoor_score": 6,
        "english_level": 5,
        "nomad_score": 7.5,
        "visa_type": "tourist",
        "visa_duration_days": 90,
        "timezone": "UTC-3",
    },
    # Middle East
    {
        "city": "Dubai",
        "country": "UAE",
        "country_code": "AE",
        "rent_studio": 1500,
        "rent_1br": 2200,
        "coworking": 400,
        "meal_cheap": 10,
        "meal_mid": 40,
        "coffee": 5,
        "groceries": 400,
        "transport": 100,
        "utilities": 150,
        "internet": 80,
        "gym": 100,
        "wifi_quality": 10,
        "safety_score": 10,
        "weather_score": 5,
        "nightlife_score": 6,
        "outdoor_score": 4,
        "english_level": 9,
        "nomad_score": 7,
        "visa_type": "dnv",
        "visa_duration_days": 365,
        "timezone": "UTC+4",
    },
]


def seed_city_costs():
    """Seed city cost of living data."""
    from backend.database import engine
    
    # Ensure tables exist
    models.Base.metadata.create_all(bind=engine)
    print("✅ Ensured database tables exist")
    
    db = SessionLocal()
    
    try:
        for city_data in CITY_DATA:
            # Check if city exists
            existing = db.query(models.CityLivingCost).filter(
                models.CityLivingCost.city == city_data["city"]
            ).first()
            
            if existing:
                # Update existing
                for key, value in city_data.items():
                    setattr(existing, key, value)
            else:
                # Create new
                city = models.CityLivingCost(
                    id=str(uuid.uuid4()),
                    **city_data
                )
                db.add(city)
        
        db.commit()
        print(f"✅ Seeded {len(CITY_DATA)} cities with cost of living data")
        
    except Exception as e:
        db.rollback()
        print(f"❌ Error seeding city data: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed_city_costs()
