"""Add extended models

Revision ID: 029958d0aa23
Revises: 112e91e71651
Create Date: 2025-12-12 12:47:35.913958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "029958d0aa23"
down_revision: Union[str, None] = "112e91e71651"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "community_tasks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("assignee_id", sa.String(), nullable=True),
        sa.Column("reward", sa.Integer(), nullable=True),
        sa.Column("xp_category", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_community_tasks_id"), "community_tasks", ["id"], unique=False
    )
    op.create_table(
        "experiences",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("theme", sa.String(), nullable=True),
        sa.Column("mission", sa.Text(), nullable=True),
        sa.Column("curator_id", sa.String(), nullable=True),
        sa.Column("start_date", sa.String(), nullable=True),
        sa.Column("end_date", sa.String(), nullable=True),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column("price_usd", sa.Float(), nullable=True),
        sa.Column("listing_ids", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("amenities", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("activities", sa.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_experiences_id"), "experiences", ["id"], unique=False)
    op.create_table(
        "hubs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("mission", sa.Text(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("logo", sa.String(), nullable=True),
        sa.Column("charter", sa.Text(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column("sustainability_score", sa.Integer(), nullable=True),
        sa.Column("member_ids", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("listing_ids", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("amenity_ids", sa.ARRAY(sa.String()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hubs_id"), "hubs", ["id"], unique=False)
    op.create_table(
        "neighborhoods",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column("cost_of_living_index", sa.Integer(), nullable=True),
        sa.Column("walkability_score", sa.Integer(), nullable=True),
        sa.Column("safety_score", sa.Integer(), nullable=True),
        sa.Column("visa_friendliness", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_neighborhoods_id"), "neighborhoods", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_neighborhoods_id"), table_name="neighborhoods")
    op.drop_table("neighborhoods")
    op.drop_index(op.f("ix_hubs_id"), table_name="hubs")
    op.drop_table("hubs")
    op.drop_index(op.f("ix_experiences_id"), table_name="experiences")
    op.drop_table("experiences")
    op.drop_index(op.f("ix_community_tasks_id"), table_name="community_tasks")
    op.drop_table("community_tasks")
    # ### end Alembic commands ###
