"""Add Listing Details

Revision ID: 21deb774caa0
Revises: 029958d0aa23
Create Date: 2025-12-12 12:49:54.831597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "21deb774caa0"
down_revision: Union[str, None] = "029958d0aa23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("listings", sa.Column("guest_capacity", sa.Integer(), nullable=True))
    op.add_column("listings", sa.Column("bedrooms", sa.Integer(), nullable=True))
    op.add_column("listings", sa.Column("bathrooms", sa.Integer(), nullable=True))
    op.add_column("listings", sa.Column("hub_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("listings", "hub_id")
    op.drop_column("listings", "bathrooms")
    op.drop_column("listings", "bedrooms")
    op.drop_column("listings", "guest_capacity")
    # ### end Alembic commands ###
