"""add_phase7_models

Revision ID: 2275f61eb986
Revises: ffc849955a97
Create Date: 2025-12-12 13:55:43.711063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2275f61eb986"
down_revision: Union[str, None] = "ffc849955a97"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "journeys",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("total_budget_usd", sa.Float(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("preferences", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_journeys_id"), "journeys", ["id"], unique=False)
    op.create_index(op.f("ix_journeys_user_id"), "journeys", ["user_id"], unique=False)
    op.create_table(
        "skill_requests",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("requester_id", sa.String(), nullable=True),
        sa.Column("skill_name", sa.String(), nullable=True),
        sa.Column("hub_id", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("budget_usd", sa.Float(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("matched_user_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["matched_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["requester_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_skill_requests_id"), "skill_requests", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_skill_requests_requester_id"),
        "skill_requests",
        ["requester_id"],
        unique=False,
    )
    op.create_table(
        "skills",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("rate_usd", sa.Float(), nullable=True),
        sa.Column("is_available", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_skills_id"), "skills", ["id"], unique=False)
    op.create_index(op.f("ix_skills_name"), "skills", ["name"], unique=False)
    op.create_index(op.f("ix_skills_user_id"), "skills", ["user_id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("tier", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("monthly_credits", sa.Integer(), nullable=True),
        sa.Column("used_credits", sa.Integer(), nullable=True),
        sa.Column(
            "start_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subscriptions_id"), "subscriptions", ["id"], unique=False)
    op.create_index(
        op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=True
    )
    op.create_table(
        "journey_legs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("journey_id", sa.String(), nullable=True),
        sa.Column("hub_id", sa.String(), nullable=True),
        sa.Column("listing_id", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=True),
        sa.Column("booking_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["hub_id"],
            ["hubs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["journey_id"],
            ["journeys.id"],
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_journey_legs_id"), "journey_legs", ["id"], unique=False)
    op.create_index(
        op.f("ix_journey_legs_journey_id"), "journey_legs", ["journey_id"], unique=False
    )
    op.create_table(
        "negotiations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("listing_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("original_price", sa.Float(), nullable=True),
        sa.Column("offered_price", sa.Float(), nullable=True),
        sa.Column("counter_price", sa.Float(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["listing_id"],
            ["listings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_negotiations_id"), "negotiations", ["id"], unique=False)
    op.create_index(
        op.f("ix_negotiations_listing_id"), "negotiations", ["listing_id"], unique=False
    )
    op.create_index(
        op.f("ix_negotiations_user_id"), "negotiations", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_negotiations_user_id"), table_name="negotiations")
    op.drop_index(op.f("ix_negotiations_listing_id"), table_name="negotiations")
    op.drop_index(op.f("ix_negotiations_id"), table_name="negotiations")
    op.drop_table("negotiations")
    op.drop_index(op.f("ix_journey_legs_journey_id"), table_name="journey_legs")
    op.drop_index(op.f("ix_journey_legs_id"), table_name="journey_legs")
    op.drop_table("journey_legs")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_skills_user_id"), table_name="skills")
    op.drop_index(op.f("ix_skills_name"), table_name="skills")
    op.drop_index(op.f("ix_skills_id"), table_name="skills")
    op.drop_table("skills")
    op.drop_index(op.f("ix_skill_requests_requester_id"), table_name="skill_requests")
    op.drop_index(op.f("ix_skill_requests_id"), table_name="skill_requests")
    op.drop_table("skill_requests")
    op.drop_index(op.f("ix_journeys_user_id"), table_name="journeys")
    op.drop_index(op.f("ix_journeys_id"), table_name="journeys")
    op.drop_table("journeys")
    # ### end Alembic commands ###
