"""fix_host_earnings_and_phase9

Revision ID: 7b491e3586d0
Revises: bb4b43280695
Create Date: 2025-12-18 21:20:57.111020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7b491e3586d0"
down_revision: Union[str, None] = "bb4b43280695"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("host_earnings", sa.Column("source_id", sa.String(), nullable=True))
    op.add_column(
        "host_earnings", sa.Column("gross_amount_usd", sa.Float(), nullable=True)
    )
    op.add_column(
        "host_earnings", sa.Column("platform_fee_usd", sa.Float(), nullable=True)
    )
    op.add_column(
        "host_earnings", sa.Column("net_amount_usd", sa.Float(), nullable=True)
    )
    op.add_column("host_earnings", sa.Column("status", sa.String(), nullable=True))
    op.add_column(
        "host_earnings", sa.Column("payout_date", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "host_earnings",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.drop_column("votes", "payout_date")
    op.drop_column("votes", "net_amount_usd")
    op.drop_column("votes", "gross_amount_usd")
    op.drop_column("votes", "source_id")
    op.drop_column("votes", "platform_fee_usd")
    op.drop_column("votes", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "votes", sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "votes",
        sa.Column(
            "platform_fee_usd",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "votes",
        sa.Column("source_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "votes",
        sa.Column(
            "gross_amount_usd",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "votes",
        sa.Column(
            "net_amount_usd",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "votes",
        sa.Column(
            "payout_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("host_earnings", "created_at")
    op.drop_column("host_earnings", "payout_date")
    op.drop_column("host_earnings", "status")
    op.drop_column("host_earnings", "net_amount_usd")
    op.drop_column("host_earnings", "platform_fee_usd")
    op.drop_column("host_earnings", "gross_amount_usd")
    op.drop_column("host_earnings", "source_id")
    # ### end Alembic commands ###
