"""Add OTA models

Revision ID: 95be11be9fd1
Revises: 7b491e3586d0
Create Date: 2025-12-27 06:30:28.106084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95be11be9fd1"
down_revision: Union[str, None] = "7b491e3586d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ota_providers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("api_endpoint", sa.String(), nullable=True),
        sa.Column("commission_rate", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("credentials_encrypted", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "external_listings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("provider_id", sa.String(), nullable=True),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("url", sa.String(), nullable=True),
        sa.Column("price_per_night", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("amenities", sa.ARRAY(sa.String()), nullable=True),
        sa.Column("last_synced", sa.DateTime(), nullable=True),
        sa.Column("availability_cache", sa.JSON(), nullable=True),
        sa.Column("pricing_cache", sa.JSON(), nullable=True),
        sa.Column("images", sa.ARRAY(sa.String()), nullable=True),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["ota_providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ota_bookings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("external_listing_id", sa.String(), nullable=True),
        sa.Column("provider_id", sa.String(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("total_price", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(), nullable=True),
        sa.Column("commission_earned", sa.Float(), nullable=True),
        sa.Column("booking_status", sa.String(), nullable=True),
        sa.Column("external_booking_ref", sa.String(), nullable=True),
        sa.Column("payment_status", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["external_listing_id"],
            ["external_listings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["ota_providers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_foreign_key(None, "host_earnings", "users", ["host_id"], ["id"])
    op.create_foreign_key(None, "journey_legs", "hubs", ["hub_id"], ["id"])
    op.create_foreign_key(None, "journeys", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "listings", "users", ["owner_id"], ["id"])
    op.create_foreign_key(None, "negotiations", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "notifications", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "proposals", "users", ["author_id"], ["id"])
    op.create_foreign_key(None, "reviews", "users", ["author_id"], ["id"])
    op.create_foreign_key(None, "skill_requests", "users", ["matched_user_id"], ["id"])
    op.create_foreign_key(None, "skill_requests", "users", ["requester_id"], ["id"])
    op.create_foreign_key(None, "skills", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "spending_records", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "subscriptions", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "votes", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "votes", type_="foreignkey")
    op.drop_constraint(None, "subscriptions", type_="foreignkey")
    op.drop_constraint(None, "spending_records", type_="foreignkey")
    op.drop_constraint(None, "skills", type_="foreignkey")
    op.drop_constraint(None, "skill_requests", type_="foreignkey")
    op.drop_constraint(None, "skill_requests", type_="foreignkey")
    op.drop_constraint(None, "reviews", type_="foreignkey")
    op.drop_constraint(None, "proposals", type_="foreignkey")
    op.drop_constraint(None, "notifications", type_="foreignkey")
    op.drop_constraint(None, "negotiations", type_="foreignkey")
    op.drop_constraint(None, "listings", type_="foreignkey")
    op.drop_constraint(None, "journeys", type_="foreignkey")
    op.drop_constraint(None, "journey_legs", type_="foreignkey")
    op.drop_constraint(None, "host_earnings", type_="foreignkey")
    op.drop_table("ota_bookings")
    op.drop_table("external_listings")
    op.drop_table("ota_providers")
    # ### end Alembic commands ###
