"""Add critical database indexes

Revision ID: b92dc1fa17ca
Revises: 95be11be9fd1
Create Date: 2026-01-05 11:17:08.910788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b92dc1fa17ca"
down_revision: Union[str, None] = "95be11be9fd1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_booking_created_at", "bookings", ["created_at"], unique=False)
    op.create_index(
        "idx_booking_listing_dates",
        "bookings",
        ["listing_id", "start_date", "end_date"],
        unique=False,
    )
    op.create_index(
        "idx_booking_user_dates",
        "bookings",
        ["user_id", "start_date", "end_date"],
        unique=False,
    )
    op.create_index(
        "idx_listing_location", "listings", ["city", "country"], unique=False
    )
    op.create_index("idx_listing_owner", "listings", ["owner_id"], unique=False)
    op.create_index("idx_listing_price", "listings", ["price_usd"], unique=False)
    op.create_index(
        "idx_listing_features",
        "listings",
        ["features"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index("idx_user_created_at", "users", ["created_at"], unique=False)
    op.create_index("idx_user_email", "users", ["email"], unique=False)
    op.create_index(
        "idx_user_wallet_address", "users", ["wallet_address"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_wallet_address", table_name="users")
    op.drop_index("idx_user_email", table_name="users")
    op.drop_index("idx_user_created_at", table_name="users")
    op.drop_index("idx_listing_owner", table_name="listings")
    op.drop_index("idx_listing_location", table_name="listings")
    op.drop_index("idx_listing_features", table_name="listings")
    op.drop_index("idx_listing_price", table_name="listings")
    op.drop_index("idx_booking_user_dates", table_name="bookings")
    op.drop_index("idx_booking_listing_dates", table_name="bookings")
    op.drop_index("idx_booking_created_at", table_name="bookings")
    # ### end Alembic commands ###
