"""add_phase9_models

Revision ID: bb4b43280695
Revises: 3ac69b631543
Create Date: 2025-12-18 21:20:22.118168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bb4b43280695"
down_revision: Union[str, None] = "3ac69b631543"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proposals",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("author_id", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("yes_votes", sa.Float(), nullable=True),
        sa.Column("no_votes", sa.Float(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_proposals_author_id"), "proposals", ["author_id"], unique=False
    )
    op.create_index(op.f("ix_proposals_id"), "proposals", ["id"], unique=False)
    op.create_table(
        "votes",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("proposal_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("vote_type", sa.String(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("source_id", sa.String(), nullable=True),
        sa.Column("gross_amount_usd", sa.Float(), nullable=True),
        sa.Column("platform_fee_usd", sa.Float(), nullable=True),
        sa.Column("net_amount_usd", sa.Float(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("payout_date", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["proposal_id"],
            ["proposals.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_votes_id"), "votes", ["id"], unique=False)
    op.create_index(
        op.f("ix_votes_proposal_id"), "votes", ["proposal_id"], unique=False
    )
    op.create_index(op.f("ix_votes_user_id"), "votes", ["user_id"], unique=False)
    op.drop_column("host_earnings", "payout_date")
    op.drop_column("host_earnings", "status")
    op.drop_column("host_earnings", "created_at")
    op.drop_column("host_earnings", "net_amount_usd")
    op.drop_column("host_earnings", "platform_fee_usd")
    op.drop_column("host_earnings", "source_id")
    op.drop_column("host_earnings", "gross_amount_usd")
    op.add_column("listings", sa.Column("virtual_tour_url", sa.String(), nullable=True))
    op.add_column("listings", sa.Column("ar_model_url", sa.String(), nullable=True))
    op.add_column("users", sa.Column("wallet_address", sa.String(), nullable=True))
    op.add_column("users", sa.Column("reputation_score", sa.Integer(), nullable=True))
    op.add_column(
        "users", sa.Column("is_verified_on_chain", sa.Boolean(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_verified_on_chain")
    op.drop_column("users", "reputation_score")
    op.drop_column("users", "wallet_address")
    op.drop_column("listings", "ar_model_url")
    op.drop_column("listings", "virtual_tour_url")
    op.add_column(
        "host_earnings",
        sa.Column(
            "gross_amount_usd",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "host_earnings",
        sa.Column("source_id", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "host_earnings",
        sa.Column(
            "platform_fee_usd",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "host_earnings",
        sa.Column(
            "net_amount_usd",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "host_earnings",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "host_earnings",
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "host_earnings",
        sa.Column(
            "payout_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.drop_index(op.f("ix_votes_user_id"), table_name="votes")
    op.drop_index(op.f("ix_votes_proposal_id"), table_name="votes")
    op.drop_index(op.f("ix_votes_id"), table_name="votes")
    op.drop_table("votes")
    op.drop_index(op.f("ix_proposals_id"), table_name="proposals")
    op.drop_index(op.f("ix_proposals_author_id"), table_name="proposals")
    op.drop_table("proposals")
    # ### end Alembic commands ###
