"""add_phase8_models

Revision ID: f76a7f2c6222
Revises: 2275f61eb986
Create Date: 2025-12-12 14:03:16.506798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f76a7f2c6222"
down_revision: Union[str, None] = "2275f61eb986"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "experience_bookings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("experience_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("booking_date", sa.DateTime(), nullable=True),
        sa.Column("num_guests", sa.Integer(), nullable=True),
        sa.Column("total_price_usd", sa.Float(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["experience_id"],
            ["experiences.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_experience_bookings_experience_id"),
        "experience_bookings",
        ["experience_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_experience_bookings_id"), "experience_bookings", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_experience_bookings_user_id"),
        "experience_bookings",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "host_earnings",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("host_id", sa.String(), nullable=True),
        sa.Column("source_type", sa.String(), nullable=True),
        sa.Column("source_id", sa.String(), nullable=True),
        sa.Column("gross_amount_usd", sa.Float(), nullable=True),
        sa.Column("platform_fee_usd", sa.Float(), nullable=True),
        sa.Column("net_amount_usd", sa.Float(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.Column("payout_date", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["host_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_host_earnings_host_id"), "host_earnings", ["host_id"], unique=False
    )
    op.create_index(op.f("ix_host_earnings_id"), "host_earnings", ["id"], unique=False)
    op.create_table(
        "spending_records",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("amount_usd", sa.Float(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("date", sa.DateTime(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("booking_id", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_spending_records_date"), "spending_records", ["date"], unique=False
    )
    op.create_index(
        op.f("ix_spending_records_id"), "spending_records", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_spending_records_user_id"),
        "spending_records",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_spending_records_user_id"), table_name="spending_records")
    op.drop_index(op.f("ix_spending_records_id"), table_name="spending_records")
    op.drop_index(op.f("ix_spending_records_date"), table_name="spending_records")
    op.drop_table("spending_records")
    op.drop_index(op.f("ix_host_earnings_id"), table_name="host_earnings")
    op.drop_index(op.f("ix_host_earnings_host_id"), table_name="host_earnings")
    op.drop_table("host_earnings")
    op.drop_index(
        op.f("ix_experience_bookings_user_id"), table_name="experience_bookings"
    )
    op.drop_index(op.f("ix_experience_bookings_id"), table_name="experience_bookings")
    op.drop_index(
        op.f("ix_experience_bookings_experience_id"), table_name="experience_bookings"
    )
    op.drop_table("experience_bookings")
    # ### end Alembic commands ###
